//! 用户级 hook 壳（REQ-032 载体全原生）：thin 透传，cmd 与 sh 两载体，
//! 全部逻辑收进 hst 二进制本体（`hst hook state/token`）。部署时
//! 烘焙部署方二进制绝对路径（self update 原位替换，路径不漂）。D28 自包
//! 含设计退役记档：hst 缺位或故障时 shell 退出码非 2，agent 侧按非阻塞
//! 错误处理 = fail-open（状态通道回落 unknown）；M060a 白名单语义由 hst
//! 本体内化（token 腿 exit 硬约束 0 与 2，仅自判 block 出 2）。
//! grok 的 Windows 单路径包装（M048）保留：包装烘焙 agent 参转调 thin
//! cmd。Windows 注册走 thin ps1 一行壳（REQ-032 评审 F2 方案③，D39 三壳
//! 通吃形 powershell.exe -File <正斜杠>）；.cmd 只留 grok 包装与手工面。

use std::path::PathBuf;

/// thin sh 壳生成（REQ-032，用户令「sh要兼容zsh和bash」）：shebang 按宿主
/// shell（mac zsh、其余 bash；`#!/usr/bin/env` 形两解释器都成立），body
/// 是 POSIX 基线（exec 加位置参），sh 加 zsh 加 bash 三壳语义一致；
/// stdin 经 exec 透传。
pub fn thin_sh(exe: &str, leg: &str, shell: &str) -> String {
    format!(
        "#!/usr/bin/env {shell}\n# generated by hst init; rerun hst init to sync (REQ-032 thin pass-through)\nexec \"{exe}\" hook {leg} --agent \"$1\"\n"
    )
}

/// thin cmd 壳生成（REQ-032）：`"<exe>" hook <腿> --agent %1`，stdin 由
/// cmd 子进程继承。
pub fn thin_cmd(exe: &str, leg: &str) -> String {
    format!(
        "@echo off\r\nrem generated by hst init; rerun hst init to sync (REQ-032 thin pass-through)\r\n\"{exe}\" hook {leg} --agent %1\r\nexit /b %errorlevel%\r\n"
    )
}

/// thin ps1 壳生成（REQ-032 评审 F2 方案③：一行壳 `& "<exe>" hook <腿>
/// --agent $args[0]`，逻辑全在 hst 本体；走 D39 三壳通吃形
/// powershell.exe -NoProfile -File <正斜杠路径>）。BOM 落盘语义同 D39。
pub fn thin_ps1(exe: &str, leg: &str) -> String {
    let exe_fwd = exe.replace('\\', "/");
    format!(
        "# generated by hst init; rerun hst init to sync (REQ-032 thin pass-through)\n& \"{exe_fwd}\" hook {leg} --agent $args[0]\nexit $LASTEXITCODE\n"
    )
}

/// grok 单路径包装生成（M048：Windows grok 只认可整串 spawn 的单路径；
/// 包装烘焙 agent 参转调 thin cmd）。
pub fn grok_wrapper(name: &str) -> String {
    format!(
        "@echo off\r\nrem generated by hst init; rerun hst init to sync (REQ-032 grok wrapper)\r\n\"%~dp0{name}.cmd\" grok\r\nexit /b %errorlevel%\r\n"
    )
}

fn crlf(s: &str) -> String {
    s.replace("\r\n", "\n").replace('\n', "\r\n")
}

/// 的写前比对面（细则见模块文档与集成测试）。
fn write_if_changed(path: &std::path::Path, content: &str) -> Result<bool, String> {
    if std::fs::read_to_string(path)
        .map(|old| old == content)
        .unwrap_or(false)
    {
        return Ok(false);
    }
    std::fs::write(path, content).map_err(|e| format!("{}: {e}", path.display()))?;
    Ok(true)
}

/// 宿主 shell 选择（M060b 抽出成映射）：macOS 落 zsh shebang（缺
/// /usr/bin/bash 的兜底；两 shebang 皆兼容），其余 bash。
pub fn host_shell() -> &'static str {
    if cfg!(target_os = "macos") {
        "zsh"
    } else {
        "bash"
    }
}

/// # Errors
///
/// 失败返回 `String` 错误（路径与原因；网络与解析类见模块文档）。
/// 部署 shim 文件集到 hst 自管根的 `hooks/`（D28 用户级常驻：
/// `<hst_home>/hooks/`，调用方传 `install::hst_home()`；测试传临时根）。
/// 三份脚本全侧落齐（跨 OS 共享并存：Windows init 也备好 .sh、Unix init
/// 也备好 .cmd；+x 只在 Unix 生效）。cmd 主 shim按 jq 探测选形态（D27
/// 的用户裁定面（细则见模块文档与集成测试）。
/// 返回 (实写路径, 警告)。
pub fn deploy_shims(root: &std::path::Path) -> Result<(Vec<PathBuf>, Vec<String>), String> {
    deploy_shims_with(root, host_shell())
}

/// # Errors
///
/// 失败返回 `String` 错误（路径与原因；网络与解析类见模块文档）。
/// 壳部署（REQ-032 thin 透传面）：state/token 两腿 sh 加 ps1 加 cmd 三
/// 载体加 grok 两包装，exe 烘焙部署方 current_exe 绝对路径；幂等内容判
/// 等；oma 旧名件与 pentest 退役件清扫。
pub fn deploy_shims_with(
    root_param: &std::path::Path,
    shell: &str,
) -> Result<(Vec<PathBuf>, Vec<String>), String> {
    let dir = root_param.join("hooks");
    std::fs::create_dir_all(&dir).map_err(|e| format!("{}: {e}", dir.display()))?;
    let cur = std::env::current_exe().ok();
    let exe = shim_exe_path(cur.as_deref());
    let mut extra_warns: Vec<String> = Vec::new();
    // REQ-043 改进 3：生成器为仓内开发构建位时告警（壳已回落装位，不阻断）。
    if cur.is_some_and(|c| {
        let s = c.display().to_string();
        s.contains("/target/debug/")
            || s.contains("\\target\\debug\\")
            || s.contains("/target/release/")
            || s.contains("\\target\\release\\")
    }) {
        extra_warns.push(format!(
            "shim exe fallback: generator is a dev build, shims baked to \"{exe}\" (rerun bare hst init from an installed binary)"
        ));
    }
    let (wrote, mut warns) = deploy_shims_with_exe(root_param, shell, &exe)?;
    warns.extend(extra_warns);
    Ok((wrote, warns))
}

/// REQ-043（总台派单实战爆雷）：exe 烘焙安全序——current_exe 落在仓内
/// 开发构建位（`/target/debug/` 加 `/target/release/` 族，正反斜杠形）
/// 时不烘焙（cargo clean 即断链，2026-10-02 六件喷屏实证），回落装位
/// 探测（unix 家目录 `.local/bin`，win `ohmyenv/hst` 族，再 PATH 首个
/// `hst`），全落空回落裸名（PATH 相对，self update 不受影响）。正装
/// current_exe 照旧绝对路径烘焙（REQ-032 原位替换路径不漂设计保持）。
fn shim_exe_path(current: Option<&std::path::Path>) -> String {
    let dev_form = |p: &str| {
        p.contains("/target/debug/")
            || p.contains("\\target\\debug\\")
            || p.contains("/target/release/")
            || p.contains("\\target\\release\\")
    };
    if let Some(cur) = current {
        let s = cur.display().to_string();
        if !s.is_empty() && !dev_form(&s) {
            return s;
        }
    }
    if let Ok(home) = crate::pathutil::user_home() {
        let cand = if cfg!(windows) {
            home.join(".local").join("bin").join("hst.exe")
        } else {
            home.join(".local").join("bin").join("hst")
        };
        if cand.is_file() {
            return cand.display().to_string();
        }
    }
    if let Some(found) = crate::pathutil::find_on_path("hst") {
        let s = found.display().to_string();
        if !dev_form(&s) {
            return s;
        }
    }
    "hst".to_string()
}

/// deploy_shims_with 的 exe 注入形（REQ-043 可测面）。
pub fn deploy_shims_with_exe(
    root_param: &std::path::Path,
    shell: &str,
    exe: &str,
) -> Result<(Vec<PathBuf>, Vec<String>), String> {
    let dir = root_param.join("hooks");
    std::fs::create_dir_all(&dir).map_err(|e| format!("{}: {e}", dir.display()))?;
    let mut wrote: Vec<PathBuf> = Vec::new();
    let mut warns = Vec::new();
    for (leg, stem) in [("state", "hst-state"), ("token", "hst-token")] {
        let sh = dir.join(format!("{stem}.sh"));
        if write_if_changed(&sh, &thin_sh(&exe, leg, shell))? {
            wrote.push(sh.clone());
        }
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let _ = std::fs::set_permissions(&sh, std::fs::Permissions::from_mode(0o755));
        }
        let ps1 = dir.join(format!("{stem}.ps1"));
        if write_if_changed(&ps1, &format!("\u{feff}{}", thin_ps1(&exe, leg)))? {
            wrote.push(ps1);
        }
        let cmd = dir.join(format!("{stem}.cmd"));
        if write_if_changed(&cmd, &crlf(&thin_cmd(&exe, leg)))? {
            wrote.push(cmd);
        }
        let grok = dir.join(format!("{stem}-grok.cmd"));
        if write_if_changed(&grok, &crlf(&grok_wrapper(stem)))? {
            wrote.push(grok);
        }
    }
    // REQ-032 退役清扫：旧 ps1 载体与 oma 旧名件；REQ-031 退役清扫：
    // pentest 腿四件（2026-09-27 用户令去渗透授权功能）。带生成标记才删，
    // 防误删用户自置同名文件。
    for legacy in [
        "oma-state.cmd",
        "oma-state-grok.cmd",
        "oma-state.sh",
        "oma-state.ps1",
        "hst-pentest.sh",
        "hst-pentest.ps1",
        "hst-pentest.cmd",
        "hst-pentest-grok.cmd",
    ] {
        let p = dir.join(legacy);
        if p.exists() {
            let ours = std::fs::read_to_string(&p)
                .map(|t| t.contains("generated by hst init") || t.contains("generated by oma"))
                .unwrap_or(false);
            if !ours {
                continue;
            }
            match std::fs::remove_file(&p) {
                Ok(()) => warns.push(format!("retired legacy shim {}", p.display())),
                Err(e) => warns.push(format!("could not retire legacy shim {}: {e}", p.display())),
            }
        }
    }
    Ok((wrote, warns))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn shim_exe_path_falls_back_from_dev_forms() {
        // REQ-043：开发构建位不烘焙（cargo clean 断链事故形）；正装照旧；
        // current 缺失走回落链不炸。
        let dev = std::path::Path::new("/x/target/debug/hst");
        assert_ne!(shim_exe_path(Some(dev)), "/x/target/debug/hst");
        let dev_win = std::path::Path::new("C:\\r\\target\\release\\hst.exe");
        assert_ne!(
            shim_exe_path(Some(dev_win)),
            "C:\\r\\target\\release\\hst.exe"
        );
        let ok = std::path::Path::new("/usr/local/bin/hst");
        assert_eq!(shim_exe_path(Some(ok)), "/usr/local/bin/hst");
        assert!(!shim_exe_path(None).is_empty());
    }

    /// 独占临时目录（行为测试用）。
    fn scratch(tag: &str) -> std::path::PathBuf {
        let p = std::env::temp_dir().join(format!(
            "hst-shim-{tag}-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_millis()
        ));
        let _ = std::fs::remove_dir_all(&p);
        std::fs::create_dir_all(&p).unwrap();
        p
    }

    #[test]
    fn thin_shells_carry_baked_exe_and_leg() {
        // REQ-032：thin 透传壳烘焙 exe 绝对路径与腿名，无任何 pwsh 串。
        let sh = thin_sh("/opt/hst", "state", "bash");
        assert!(sh.starts_with("#!/usr/bin/env bash\n"), "{sh}");
        let zsh = thin_sh("/opt/hst", "state", "zsh");
        assert!(zsh.starts_with("#!/usr/bin/env zsh\n"), "{zsh}");
        assert!(
            zsh.contains("exec \"/opt/hst\" hook state"),
            "POSIX body: {zsh}"
        );
        assert!(
            sh.contains("exec \"/opt/hst\" hook state --agent \"$1\""),
            "{sh}"
        );
        assert!(!sh.contains("powershell") && !sh.contains("pwsh"), "{sh}");
        let cmd = thin_cmd("C:\\tools\\hst.exe", "token");
        assert!(cmd.starts_with("@echo off\r\n"), "{cmd}");
        assert!(
            cmd.contains("\"C:\\tools\\hst.exe\" hook token --agent %1"),
            "{cmd}"
        );
        let w = grok_wrapper("hst-state");
        assert!(w.contains("\"%~dp0hst-state.cmd\" grok"), "{w}");
        let ps1 = thin_ps1("C:\\tools\\hst.exe", "state");
        assert!(
            ps1.contains("& \"C:/tools/hst.exe\" hook state --agent $args[0]"),
            "{ps1}"
        );
        assert!(ps1.contains("exit $LASTEXITCODE"), "{ps1}");
    }

    #[test]
    fn deploy_shims_writes_eight_and_is_idempotent() {
        // 两腿（sh 加 ps1 加 cmd 加 grok 包装）= 八件；幂等。
        let dir = scratch("eight");
        let (wrote, warns) = deploy_shims_with(&dir, "bash").unwrap();
        assert_eq!(
            wrote.len(),
            8,
            "eight thin shells (sh/ps1/cmd x2 + grok x2): {wrote:?}"
        );
        // REQ-043：测试进程即开发构建位，告警恰在（回落装位烘焙）。
        assert!(
            warns.iter().any(|w| w.starts_with("shim exe fallback")),
            "dev-build warn present: {warns:?}"
        );
        for name in [
            "hst-state.sh",
            "hst-state.ps1",
            "hst-state.cmd",
            "hst-state-grok.cmd",
            "hst-token.sh",
            "hst-token.ps1",
            "hst-token.cmd",
            "hst-token-grok.cmd",
        ] {
            assert!(dir.join("hooks").join(name).exists(), "missing {name}");
        }
        // 第二趟幂等：零写。
        let (wrote2, _) = deploy_shims_with(&dir, "bash").unwrap();
        assert!(wrote2.is_empty(), "{wrote2:?}");
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn crlf_normalizes_without_doubling() {
        assert_eq!(crlf("a\r\nb\n"), "a\r\nb\r\n");
        assert_eq!(crlf("a\nb"), "a\r\nb");
    }

    #[test]
    fn write_if_changed_skips_identical_content() {
        let dir = scratch("wic");
        let p = dir.join("f");
        assert!(write_if_changed(&p, "x").unwrap());
        assert!(!write_if_changed(&p, "x").unwrap());
        assert!(write_if_changed(&p, "y").unwrap());
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn thin_sh_passes_stdin_and_exit_semantics() {
        // REQ-032 行为面：thin sh 透传 stdin 与退出码（hst 本体 exit 0 与
        // 2 直通；非 2 的故障码也直传——agent 侧按非阻塞错误处理）。
        use std::io::Write;
        use std::os::unix::fs::PermissionsExt;
        use std::process::{Command, Stdio};
        let dir = scratch("thin-run");
        let fake = dir.join("fake-hst");
        std::fs::write(&fake, "#!/bin/sh\ncat >/dev/null\nexit 2\n").unwrap();
        std::fs::set_permissions(&fake, std::fs::Permissions::from_mode(0o755)).unwrap();
        let shim = dir.join("hst-token.sh");
        std::fs::write(&shim, thin_sh(fake.to_str().unwrap(), "token", "bash")).unwrap();
        std::fs::set_permissions(&shim, std::fs::Permissions::from_mode(0o755)).unwrap();
        let mut child = Command::new(&shim)
            .arg("claude")
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .spawn()
            .unwrap();
        child
            .stdin
            .take()
            .unwrap()
            .write_all(br#"{"hook_event_name":"PreToolUse"}"#)
            .unwrap();
        let out = child.wait_with_output().unwrap();
        assert_eq!(out.status.code(), Some(2), "exit 2 passes through");
        let _ = std::fs::remove_dir_all(&dir);
    }
}
